# Generated by Django 4.2.11 on 2024-03-25 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('month', models.CharField(choices=[('01', 'فروردین'), ('02', 'اردیبهشت'), ('03', 'خرداد'), ('04', 'تیر'), ('05', 'مرداد'), ('06', 'شهریور'), ('07', 'مهر'), ('08', 'ابان'), ('09', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=2)),
                ('year', models.CharField(choices=[('1403', '1403'), ('1404', '1404'), ('1405', '1405')], max_length=4)),
                ('content', models.TextField(max_length=100)),
                ('width', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('day_number', 'month', 'year', 'user')},
            },
        ),
    ]
