# Generated by Django 5.0.3 on 2024-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='height',
        ),
        migrations.RemoveField(
            model_name='day',
            name='width',
        ),
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'ابان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=2),
        ),
    ]
